# Generated by Django 5.2.17 on 2026-09-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('story', '0002_alter_beat_options_alter_beat_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='beat_take',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='story.beattake'),
        ),
        migrations.AddField(
            model_name='review',
            name='beat_take',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='story.beattake'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='role',
            field=models.CharField(choices=[('character_ref', 'Character Ref'), ('location_ref', 'Location Ref'), ('prop_ref', 'Prop Ref'), ('start_frame', 'Start Frame'), ('end_frame', 'End Frame'), ('clip', 'Clip'), ('score', 'Score'), ('voice', 'Voice'), ('episode_cut', 'Episode Cut')], max_length=32),
        ),
    ]
