# Generated by Django 5.2.17 on 2026-09-18 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('logline', models.TextField()),
                ('function_in_arc', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('outlined', 'Outlined'), ('scripted', 'Scripted'), ('segmented', 'Segmented'), ('in_production', 'In Production'), ('review', 'Review'), ('locked', 'Locked')], default='draft', max_length=24)),
                ('characters', models.ManyToManyField(blank=True, to='bible.character')),
                ('locations', models.ManyToManyField(blank=True, to='bible.location')),
                ('props', models.ManyToManyField(blank=True, to='bible.prop')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='projects.season')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('season', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('fountain', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='story.episode')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('episode', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField(help_text='~24 words of action / dialogue')),
                ('word_count', models.PositiveSmallIntegerField(default=0)),
                ('duration_seconds', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('camera', models.JSONField(default=dict)),
                ('emotion', models.CharField(blank=True, max_length=80)),
                ('dialogue', models.TextField(blank=True)),
                ('video_prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
                ('backend', models.CharField(default='google-veo-3.1', max_length=64)),
                ('take', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved_text', 'Approved Text'), ('ready_to_render', 'Ready To Render'), ('rendering', 'Rendering'), ('review', 'Review'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='draft', max_length=24)),
                ('characters', models.ManyToManyField(blank=True, to='bible.character')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bible.location')),
                ('props', models.ManyToManyField(blank=True, to='bible.prop')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='story.episode')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beats', to='story.script')),
            ],
            options={
                'ordering': ['index', 'take'],
                'unique_together': {('episode', 'index', 'take')},
            },
        ),
    ]
