# Generated by Django 5.2.17 on 2026-09-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beat',
            options={'ordering': ['index']},
        ),
        migrations.AlterUniqueTogether(
            name='beat',
            unique_together={('script', 'index')},
        ),
        migrations.AddField(
            model_name='beat',
            name='continuity',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='beat',
            name='take',
            field=models.PositiveIntegerField(default=1, help_text='Legacy display field; generations are stored in BeatTake.'),
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('time_of_day', models.CharField(blank=True, max_length=80)),
                ('lighting', models.TextField(blank=True)),
                ('continuity_state', models.JSONField(default=dict)),
                ('characters', models.ManyToManyField(blank=True, to='bible.character')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='story.episode')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bible.location')),
                ('props', models.ManyToManyField(blank=True, to='bible.prop')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='story.script')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('script', 'index')},
            },
        ),
        migrations.AddField(
            model_name='beat',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beats', to='story.scene'),
        ),
        migrations.CreateModel(
            name='BeatTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('prompt', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
                ('backend', models.CharField(blank=True, max_length=64)),
                ('uri', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('review', 'Review'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('generation_meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='story.beat')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('beat', 'number')},
            },
        ),
    ]
